### ISSUE TITLE
Regency ID in regencies and districts datasheets is mismatch

### ISSUE THREAD

**Issue by roy-bukapeta** [edwardsamuel/Wilayah-Administratif-Indonesia#2]
Halo, perkenalkan nama saya roy, saya sangat senang dengan apa yang mas edward lakukan ;)
saya sudah mencoba data dari folder csv, namun saya menemukan ketidak cocokan antara id_kabupaten yang ada di CSV kabupaten dengan id_kabupaten yang ada pada CSV kecamatan...
Nampaknya ada kelibihan karakter '0' pada kolom id_kabupaten di csv kecamatan, bisa saya langsung pull request?
Terima kasih.

**Comment by edwardsamuel** [comment]
Terima kasih atas kejeliannya Mas @roy-bukapeta. Silahkan pull request untuk memperbaikinya.

**Comment by roy-bukapeta** [comment]
Oke, terima kasih bro... data sudah dibenerin, mau push tapi permission denied @edwardsamuel ...

**Comment by edwardsamuel** [comment]
Ya, memang tidak bisa langsung push ke repo ini @roy-bukapeta. Silahkan fork terlebih dahulu, push ke repo hasil fork tersebut, dan buat pull request ke repo ini. Bisa lihat di https://www.thinkful.com/learn/github-pull-request-tutorial/#Time-to-Submit-Your-First-PR.
