### ISSUE TITLE
Postal Code?

### ISSUE THREAD

**Issue by chez14** [edwardsamuel/Wilayah-Administratif-Indonesia#7]
Is there a way to get then add postal code into it?
Thankyou!

**Comment by edwardsamuel** [comment]
Currently I couldn't find any official source. But, if anyone have, feel free to tell me or create a pull request for that.

**Comment by jayvdb** [comment]
According to http://index.okfn.org/place/indonesia/postcodes/ , it doesnt exist as open data.

**Comment by chez14** [comment]
i got a sql dump for the postal code, is it okay to add it to here? i mean, it's come from untrusted source.

**Comment by jayvdb** [comment]
Data provenance is important.  How and when was SQL data created?  If there are errors, who do we blame?  Very important if this data ends up being used in software that effects real people's lives.

I cant see any Indonesian information at https://wiki.openstreetmap.org/wiki/Free_The_Postcode or http://wiki.openstreetmap.org/wiki/Key:postal_code

@iyan31, @wonderchook, any ideas?

**Comment by int2k** [comment]
best source for post code probably only Pos Indonesia, they do have postcode search application
[Pos Indonesia](http://kodepos.posindonesia.co.id/)
unfortunately there's no way to easily take the data

**Comment by nueko** [comment]
yes, i found no open data for postalcode, so i just tricked the pos indonesia site to get it

**Comment by nueko** [comment]
sebenernya kasian situs mfd dan pos, kita selalu brute forcing search engine mereka, kenapa ga dikasih aja ya :-)

**Comment by chez14** [comment]
Mintain aja 🐧

**Comment by imam** [comment]
https://github.com/edwinkun/database-kodepos-seluruh-indonesia

Currently, I'm pretty busy, I'll try to make a pull request later whenever I have the free time (insya Allah)

**Comment by imam** [comment]
Sepertinya repository edwinkun lebih lengkap, ambil dari sana aja  :sweat_smile:

**Comment by chez14** [comment]
Yah mas, hahahah jadi promosi repo sebelah hahahaha

**Comment by edwin** [comment]
hi mas, boleh tau dipecah seperti apa?
Grouping based on province atau gimana?
